### ISSUE TITLE
pynfl.schedule requires sudo

### ISSUE THREAD

**Issue by ghost** [jeremyjbowers/nfl-stats#2]
When I run `pynfl.schedule` from the command-line with Python 2.7 I get the following traceback error:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/pynfl/schedule.py", line 97, in <module>
    l.write_data()
  File "/usr/local/lib/python2.7/site-packages/pynfl/schedule.py", line 91, in write_data
    with open('%s/schedule.json' % self.DATA_DIRECTORY, 'w') as writefile:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/pynfl/data/schedule.json'
```

 I'm not really sure why a Python script to fetch data needs to access files in `/usr/` and need superuser powers in the process.

**Comment by jeremyjbowers** [comment]
It's trying to write to a local `data/` folder inside the project root, e.g., in `/usr/local/lib/pythong2.7/site-packages/pynfl/`. I think I'll write these to `/tmp/` instead.
